### ISSUE TITLE
messages with blocks are not well displayed

### ISSUE THREAD

**Issue by svengau** [CAKE-com/pumble-node-sdk#12]
Hey, I'm trying to send the sample message provided by the library, but I only see "hello" in the Pumble channel. Does Pumble really support rich_text_section ?

Here is my sample code (I use `got` to send http queries):

```
 const response = await client.post(
      `v1/channels/${pumbleBot.channelId}/messages`,
      {
        json: {
          text: "hello2",
          blocks: [
            {
              type: "rich_text",
              elements: [
                {
                  type: "rich_text_section",
                  elements: [{ type: "link", url: "https://example.com" }],
                },
              ],
            },
            {
              type: "actions",
              elements: [
                {
                  type: "dynamic_select_menu",
                  initial_options: [],
                  min_query_length: 3,
                  onAction: "dropDown1",
                  placeholder: { text: "Select something", type: "plain_text" },
                },
              ],
            },
          ],
        } as V1.SendMessagePayload,
        throwHttpErrors: false,
        resolveBodyOnly: false,
        headers: {
          token: pumbleBot.botToken,
          "x-app-token": process.env.PUMBLE_APP_KEY,
        },
      },
    );
```

Thanks

**Comment by milos-trivundza** [comment]
Hey, thanks for reaching out.
Yes, Pumble does support rich text, but the issue here is that you're trying to send 
`{
              type: "actions",
              elements: [
                {
                  type: "dynamic_select_menu",
                  initial_options: [],
                  min_query_length: 3,
                  onAction: "dropDown1",
                  placeholder: { text: "Select something", type: "plain_text" },
                },
              ],
            }`
which is interactive block while interactive components aren't enabled yet (we're actively working on it), removing that part should fix your issue.

I've noticed that you're not using our SDK fully, please take a look at README. You can use pumble-cli to quickly create, generate and run the app (all the necessary API calls are already built in). Also, you can check out https://cake-com.github.io/pumble-node-sdk/getting-started for more details.

Feel free to reach out if you need any additional help! :)

**Comment by svengau** [comment]
Thanks for the quick feedback! And indeed, it works better without the actions block.
Still, it would be really helpful to have a few working examples because:
-  text + blocks = text is not displayed
- I don't know how blocks is structured, and I didn't find any doc or detailed examples to display some markdown texts.

**Comment by svengau** [comment]
Also, I don't use pumble-sdk:
- because it does too many things. I don't need an http server to handle slash commands, etc... I just want to oauth and send notifications from a web server,
- the doc is missing a few good basic samples, like instanciating a standalone client,
- and moreover, I want to keep the size of my app small (because serverless) and pumble-sdk relies on a few big packages (mongodb, axios, express, lodash, ajv)

That being said, I like your product, it's a good and far cheaper alternative to a well known service. :)

Also, feel free to close this ticket.

**Comment by milos-trivundza** [comment]
> text + blocks = text is not displayed

In this case, if you send blocks, the text will serve as raw content that Pumble will fall back on if something goes wrong with the blocks.

Thank you very much for your feedback. We will be improving both the SDK and the documentation in the future. :)
